---
- name: Install K3s servers
  hosts: server
  become: yes
  tasks:
    - name: Download and install k3s server
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --cluster-init --write-kubeconfig-mode 644 --disable servicelb --disable traefik" sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Copy node token to local
      fetch:
        src: /var/lib/rancher/k3s/server/node-token
        dest: ./node-token
        flat: yes
      when: inventory_hostname == groups['server'][0]

- name: Install K3s servers (joining control-plane)
  hosts: server[1:]
  become: yes
  tasks:
    - name: Install k3s server with join parameters
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --server https://{{ hostvars[groups['server'][0]]['ansible_host'] }}:6443 --token {{ lookup('file', './node-token') }} --disable servicelb --disable traefik" sh -
      args:
        creates: /usr/local/bin/k3s

- name: Install K3s agents
  hosts: agent
  become: yes
  tasks:
    - name: Install k3s agent
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars[groups['server'][0]]['ansible_host'] }}:6443 \
          K3S_TOKEN={{ lookup('file', './node-token') }} sh -
      args:
        creates: /usr/local/bin/k3s